name = "Slabcraft"
author = "ReveredOxygen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "117ce6874324b2b5dc5bdcb69aa4239f2ed6ead4dd38f2020fea1fc19fa17fd1"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
