name = "Slabcraft"
author = "ReveredOxygen"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5ee3f29edf7569b24ac243dd5975eeca44c76722940783e8c0bd4055b6feda4"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
