name = "Slabcraft"
author = "ReveredOxygen"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d225fdd3ff2998ae8379aa997b4fd1543f7d67d53a511a9bff2082e0db4834af"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
