name = "Slabcraft"
author = "ReveredOxygen"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "330edfc85ee5b207ad37e97e7938537614f93307ce27e21324c38713b7a0bc14"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
