name = "Slabcraft"
author = "ReveredOxygen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c7253668c5c426d9eea58b3827ade1e8077f97f47ab636b1ef9da1ea71dbd74"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
