name = "Slabcraft"
author = "ReveredOxygen"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29a598002db9cedce7f6a8c012a89cacef940b9fcb9fdae4c4cf9f77d0bf72b4"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
