name = "Slabcraft"
author = "ReveredOxygen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5197500c3d16187bb64c51326bbe27ba36e895ca49429a209634756bf883cd3a"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
