name = "Slabcraft"
author = "ReveredOxygen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8470a52fdf364c29c2739f70e038283e4f99920d12e271dd5a1553faa6bdb11"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
