name = "Slabcraft"
author = "ReveredOxygen"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bdfdba698ae01a94ee4fcddedc9b2f41072aa03c1d7d2eb210cefd2a8281a5e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
