name = "Slabcraft"
author = "ReveredOxygen"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75e333fe4032b1631951a387219d15c7de4b2591bdc1bd6058959dc5602ded80"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
