name = "Slabcraft"
author = "ReveredOxygen"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "649c9baa6d4ec7f004e83ee040349c56eb5dbd706e655f73f27be50d97d91b3e"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
