name = "Slabcraft"
author = "ReveredOxygen"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7f6342f137e856d82d19fab354f42c0af994076a509d17667b9e5e952db1271"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
